SELECT TOP (1000) [Customer ID]
      ,[Age]
      ,[Gender]
      ,[Item Purchased]
      ,[Category]
      ,[Purchase Amount (USD)]
      ,[Location]
      ,[Size]
      ,[Color]
      ,[Season]
      ,[Review Rating]
      ,[Subscription Status]
      ,[Shipping Type]
      ,[Discount Applied]
      ,[Promo Code Used]
      ,[Previous Purchases]
      ,[Payment Method]
      ,[Frequency of Purchases]
  FROM [customer_behavior].[dbo].[customer]



--what is the total revenue generated by male and female customer?--
select Gender,
SUM([Purchase Amount (USD)]) AS total_revenue
from customer
group by Gender;

--which customer used a discount but still spend more more than average purchase amount?--
select *
from customer
where [Discount Applied] ='Yes'
and [Purchase Amount (USD)] > (
select AVG([Purchase Amount (USD)]) from customer
);

--Which are the top 5 products with the highest average review rating?--
select top 5 [Item Purchased],
AVG([Review Rating]) as avg_rating
from customer
group by [Item Purchased]
order by avg_rating desc;

--Compare the average Purchase Amounts between Standard and Express Shipping--
select [Shipping Type],
AVG([Purchase AMount (USD)]) as avg_purchase
from customer
where [Shipping Type] in ('Standard', 'Express')
group by [Shipping Type];

--Do subscribed customers spend more? Compare average spend and total revenue --between subscribers and non-subscribers.--
SELECT TOP 5
    [Item Purchased],
    COUNT(CASE WHEN [Discount Applied] = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY [Item Purchased]
ORDER BY discount_percentage DESC;

--Which 5 products have the highest percentage of purchases with discounts applied?--
select top 5
[Item Purchased],
COUNT(case when [Discount Applied] = 'Yes' then 1 end) * 100.0 /count(*) as discount_percentage
from customer
group by [Item Purchased]
order by discount_percentage desc;

--Segment customers into New, Returning, and Loyal based on their total -- number of previous purchases, and show the count of each segment. 
SELECT 
    CASE 
        WHEN [Previous Purchases] = 0 THEN 'New'
        WHEN [Previous Purchases] BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM customer
GROUP BY 
    CASE 
        WHEN [Previous Purchases] = 0 THEN 'New'
        WHEN [Previous Purchases] BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END;

--What are the top 3 most purchased products within each category? 
with ranked_products as(
select Category,
[Item Purchased],
COUNT(8) as purchased_count,
ROW_NUMBER() over (PARTITION by Category order by count(*) desc) as rank
from customer
group by Category, [Item Purchased]
)
select* from ranked_products
where rank <= 3;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
SELECT 
    CASE 
        WHEN [Previous Purchases] > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END AS customer_type,
    [Subscription Status],
    COUNT(*) AS total_customers
FROM customer
GROUP BY 
    CASE 
        WHEN [Previous Purchases] > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END,
    [Subscription Status];

--What is the revenue contribution of each age group?
SELECT 
    CASE 
        WHEN Age < 25 THEN 'Under 25'
        WHEN Age BETWEEN 25 AND 40 THEN '25-40'
        WHEN Age BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END AS age_group,
    SUM([Purchase Amount (USD)]) AS total_revenue
FROM customer
GROUP BY 
    CASE 
        WHEN Age < 25 THEN 'Under 25'
        WHEN Age BETWEEN 25 AND 40 THEN '25-40'
        WHEN Age BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END
ORDER BY total_revenue DESC;